name: 'Poll Until'
description: 'Runs a check script repeatedly until condition is met or timeout'

inputs:
  check-script:
    description: 'Path to the check script (relative to action path, e.g., ./check-deployment-state.ps1)'
    required: true
  script-args:
    description: 'Arguments to pass to the check script (space-separated)'
    required: false
    default: ''
  max-retries:
    description: 'Maximum number of polling attempts'
    required: false
    default: '60'
  interval-seconds:
    description: 'Seconds between polling attempts'
    required: false
    default: '60'
  condition-name:
    description: 'Human-readable name of the condition being waited for'
    required: false
    default: 'condition'

runs:
  using: 'composite'
  steps:
    - name: Poll until condition met
      shell: pwsh
      run: |
        ${{ github.action_path }}/poll-until.ps1 `
          -CheckScript "${{ inputs.check-script }}" `
          -ScriptArgs "${{ inputs.script-args }}" `
          -MaxRetries ${{ inputs.max-retries }} `
          -IntervalSeconds ${{ inputs.interval-seconds }} `
          -ConditionName "${{ inputs.condition-name }}"
